[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[profile.default.optimizer_details.yulDetails]
stackAllocation = true                                        # whether to enable the improvement of allocation of stack slots for variables or not
optimizerSteps = 'dhfoDgvulfnTUtnIf'                          # the optimization steps to be applied

fs_permissions = [{ access = "read", path = "./"}]